### ISSUE TITLE
$this->getUptime();

### ISSUE THREAD

**Issue by florianprobst** [Stricted/speedport-hybrid-php-api#2]
Liefert bei mir immer eine 0. Eigentlich sollte hier die Laufzeit des Routers seit Neustart in Tagen herauskommen oder?

**Comment by Stricted** [comment]
es kommt darauf an, wenn dein router alle 24 stunden automatisch die verbindung trennt und neu verbindet dann steht da immer 0
leider bekommt man vom router nur die information wie lange und seit wann (in tagen) der router mit dem internet verbunden ist, eine andere möglichkeit eine "uptime" zu erhalten habe ich leider (noch?) nicht gefunden

**Comment by Stricted** [comment]
so habe nun den fehler gefunden, die datei LAN.json (vom router) gibt immer 0 zurück (keine ahnung warum), ich habe nun eine andere stelle gefunden an der wirklich etwas zurükgegeben wird
da ich meinen router auf "always online" stehen habe bekomme ich nun "[days_online] => 11" zurück
