### ISSUE TITLE
Connection -> changeLTEStatus

### ISSUE THREAD

**Issue by benzman81** [Stricted/speedport-hybrid-php-api#3]
Hi, just used your Code. Pretty cool and good work. But I have a question, I want to switch LTE between on and off, but the method Connection -> changeLTEStatus is throws an Exception "unstable funtion". I removed this and seems to work fine. What is the reason for this exception?

**Comment by Stricted** [comment]
i havent implemented the check for return true/false and in my tests for some reasons the router returned fail as status
feel free to test it and open an pull request

**Comment by Stricted** [comment]
https://github.com/Stricted/speedport-hybrid-php-api/commit/7ef0b760248cf13bec5c6143b044ea4b3ba8669a
