### ISSUE TITLE
Login doenset work

### ISSUE THREAD

**Issue by Acer90** [Stricted/speedport-hybrid-php-api#4]
Here are the solution.

https://github.com/melle/l33tport/compare/new-login

Please fix it.

**Comment by Stricted** [comment]
i know that it currently dosent work and i know what i have to change to get it working again
will take a look into that soon

**Comment by Acer90** [comment]
Danke schön :-D

Dann brauchen Sie ja meinen Forum-Post nicht zu beachten,

**Comment by Stricted** [comment]
könntest du das mal bitte testen? https://github.com/Stricted/speedport-hybrid-php-api/commit/5575d0177b3669ed808101e28fca40440a8c2be9
habe selber aktuell nicht die neue fw auf dem sph kann es daher leider nicht testen

**Comment by Acer90** [comment]
Fatal error: Uncaught exception 'RouterException' with message 'empty response' in \speedport-hybrid-php-api-master\SpeedportHybrid.class.php:149 Stack 
trace: 
#0 \speedport-hybrid-php-api-master\lib\trait\Login.class.php(98): SpeedportHybrid->sendRequest('html/content/ov...', Array, true) 
#1 \speedport-hybrid-php-api-master\lib\trait\Login.class.php(45): SpeedportHybrid->getChallenge() 
#2 \speedport-hybrid-php-api-master\tests\config.php(6): SpeedportHybrid->login('***') 
#3 \speedport-hybrid-php-api-master\tests\dsl.php(2): require_once('C:\Users\***...') 
#4 {main} thrown in \speedport-hybrid-php-api-master\SpeedportHybrid.class.php on line 149

Login und Pfad habe ich entfernt das ist die meldung

**Comment by Stricted** [comment]
https://github.com/Stricted/speedport-hybrid-php-api/commit/a2bacc49116d44aee2c3d294dbfa8985a06b4a62
bitte nochmal testen

**Comment by Acer90** [comment]
Fatal error: Uncaught exception 'RouterException' with message 'you musst be logged in to use this method'

**Comment by Stricted** [comment]
https://github.com/Stricted/speedport-hybrid-php-api/commit/36484600d25a9eddad1018c142c9b648a33dddaf
sollte nun funktionieren

**Comment by Acer90** [comment]
Danke es sieht gut aus

**Comment by Stricted** [comment]
sollte es auch, habe jetzt extra mir der neuen fw getestet
